### ISSUE TITLE
Require opt-in to share personal information with all members

### ISSUE THREAD

**Issue by Levis92** [cthit/Gamma#764]
At the moment all contact data and CID is shared with all members. It is a better privacy practice to use opt-in on what information is shared and with who. It also needs to be more clear to the users who can access their information and why.

![IMG_0311](https://user-images.githubusercontent.com/16805105/88418983-abfddc80-cde4-11ea-9fbb-4fc399305aed.jpeg)

A cool thing is if it would be possible to have a cloaked email that forwards to users personal address. Something like: `uuid@cloaked.chalmers.it`. Then you can revoke that address and create a new one if needed. Apple uses something like it in their `Sign in with Apple` auth service for example.

I’m available to discuss this if help is wanted/needed.

**Comment by Portals** [comment]
I like the idea of a cloaked email, but I will skip it for this issue. Please open it as a separate issue since it's a pretty big feature. 

I think the best solution forward is to update the user agreement to better reflect what kind of information shared with other users. That everything that's added to Gamma is also accessible to other Gamma users and applications that they have accepted. And also hide users to other normal users that have not accepted a new user agreement.

**Comment by Portals** [comment]
This will be resolved in the future with a new user agreement and also enforcing it. Please follow #703 and #758 for more information.
